"""create papers table

Revision ID: af37f4204726
Revises: 
Create Date: 2026-08-26 16:48:05.158161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af37f4204726'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('arxiv_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('authors', sa.JSON(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=False),
    sa.Column('published', sa.DateTime(), nullable=False),
    sa.Column('parsed_content', sa.JSON(), nullable=False),
    sa.Column('indexed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('arxiv_id')
    )
    op.create_index('ix_papers_published', 'papers', ['published'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_papers_published', table_name='papers')
    op.drop_table('papers')
    # ### end Alembic commands ###
